// <auto-generated />
using System;
using BridgetItService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BridgetItService.Migrations
{
    [DbContext(typeof(BridgedItContext))]
    [Migration("20240201015448_health")]
    partial class health
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BridgetItService.Models.Database.DBProduct", b =>
                {
                    b.Property<string>("Sku")
                        .HasColumnType("text");

                    b.Property<int>("AttributeSetId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IsInStock")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<long?>("Qty")
                        .HasColumnType("bigint");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("TypeId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("Visibility")
                        .HasColumnType("integer");

                    b.HasKey("Sku");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("BridgetItService.Models.Database.DBTransaction", b =>
                {
                    b.Property<string>("InfinityTransactionId")
                        .HasColumnType("text");

                    b.Property<string>("MagentoTransactionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("PaymentValue")
                        .HasColumnType("double precision");

                    b.Property<string>("SalesPersonCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("InfinityTransactionId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("BridgetItService.Models.Database.Health", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("LastRun")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Health");
                });
#pragma warning restore 612, 618
        }
    }
}
